import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const workspaceNodeModules = path.resolve(__dirname, '../node_modules')

// Where the rewrites below forward API traffic. Read at server start rather than
// baked in: next.config is plain Node config, not compiled by Next, so this is
// one of the few places a runtime value is available to the web container.
//
// In the deployed stacks nginx matches /v1 and /uploads ahead of Next and
// proxies straight to the API, so these rewrites are a fallback there — but the
// fallback has to point at the api service, not 127.0.0.1, which inside the web
// container is the web container.
const localApiOrigin = (
  process.env.API_PROXY_ORIGIN ||
  process.env.NEXT_PUBLIC_API_URL ||
  'http://127.0.0.1:4000'
).replace(/\/+$/, '')

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  // Emit a self-contained server (.next/standalone) so the Docker runtime doesn't
  // depend on the pnpm workspace node_modules symlink layout.
  output: 'standalone',
  // The app lives in a pnpm workspace; trace from the repo root so workspace
  // dependencies are bundled into the standalone output.
  outputFileTracingRoot: path.resolve(__dirname, '..'),
  experimental: {
    // src/lib/claimTypes.ts re-exports runtime values from ../../../shared, which
    // sits outside the Next root. Without this the SWC loader is never applied to
    // those files and webpack tries to parse raw TypeScript as JavaScript.
    externalDir: true,
  },
  /**
   * Framing policy.
   *
   * The educational tools under /tools are meant to be embedded by clinics,
   * educators, and law libraries — that is the point of the embed snippets on
   * those pages. Everything else has no reason to appear in someone else's frame,
   * and until now nothing did: no framing header was set anywhere, so the whole
   * site including the dashboard and login could be framed by any origin.
   *
   * The two rules must not both match a request. Browsers intersect multiple
   * Content-Security-Policy headers and apply the most restrictive result, so an
   * overlap would silently un-embed the tools. Hence the negative lookahead —
   * verify with `curl -I` on a tool route and a normal one after changing this.
   *
   * X-Frame-Options is sent only on the restricted routes. It cannot express an
   * allowlist of arbitrary third parties, so on the tool routes its presence
   * would block exactly the embedding we want.
   */
  async headers() {
    return [
      {
        source: '/tools/:path*',
        headers: [{ key: 'Content-Security-Policy', value: 'frame-ancestors *' }],
      },
      {
        source: '/((?!tools/).*)',
        headers: [
          { key: 'Content-Security-Policy', value: "frame-ancestors 'self'" },
          { key: 'X-Frame-Options', value: 'SAMEORIGIN' },
        ],
      },
    ]
  },
  async redirects() {
    return [
      // Retired public URL. The SPA already redirected in the browser, but that
      // returns 200 to a crawler and passes no ranking signal; this makes it a
      // real redirect. 301 rather than the 308 `permanent: true` emits, because
      // third-party SEO tooling reads 301 more consistently.
      { source: '/for-attorneys', destination: '/attorney-network', statusCode: 301 },
      // Fifteen carrier pages that were three documents. Each family was
      // generated by mapping a carrier array over one template literal, and
      // scored 1.000 similarity with the carrier name masked — identical, not
      // merely alike. They are consolidated into two guides organised by denial
      // reason and by claim stage, which is the axis we can actually say
      // something specific about.
      ...[
        'state-farm', 'geico', 'progressive', 'allstate', 'farmers',
        'usaa', 'liberty-mutual', 'mercury', 'travelers', 'nationwide',
      ].map((carrier) => ({
        source: `/insurance/${carrier}-denied-claim`,
        destination: '/insurance/claim-denial',
        statusCode: 301,
      })),
      ...['state-farm', 'geico', 'progressive', 'allstate', 'usaa'].map((carrier) => ({
        source: `/insurance/${carrier}-settlement-process`,
        destination: '/insurance/settlement-process',
        statusCode: 301,
      })),
      // Eight case-strength pages generated from a single seed, where only the
      // title and one clause of the description differed — 0.909 similarity
      // with the crash type masked, and no impressions in three months. The
      // crash-type detail survives as FAQ entries on the consolidated page.
      // Two used a directory slug and six a hyphenated one, which is why the
      // sources are spelled out rather than mapped over one pattern.
      ...[
        '/case-strength/rear-end-accident',
        '/case-strength/red-light-accident',
        '/case-strength-hit-and-run',
        '/case-strength-uninsured-driver',
        '/case-strength-commercial-truck',
        '/case-strength-rideshare-accident',
        '/case-strength-motorcycle-accident',
        '/case-strength-pedestrian-accident',
      ].map((source) => ({ source, destination: '/case-strength', statusCode: 301 })),
    ]
  },
  // Local/LAN: browser calls same-origin `/v1/*`; Next proxies to the API.
  // Avoids CORS + Chromium Private Network Access when using the Network URL.
  async rewrites() {
    return [
      {
        source: '/v1/:path*',
        destination: `${localApiOrigin}/v1/:path*`,
      },
      {
        source: '/uploads/:path*',
        destination: `${localApiOrigin}/uploads/:path*`,
      },
      {
        source: '/health',
        destination: `${localApiOrigin}/health`,
      },
    ]
  },
  webpack: (config) => {
    // Force the web app to use the same React runtime that Next resolves from the workspace root.
    config.resolve.alias = {
      ...config.resolve.alias,
      react: path.resolve(workspaceNodeModules, 'react'),
      'react/jsx-runtime': path.resolve(workspaceNodeModules, 'react/jsx-runtime.js'),
      'react/jsx-dev-runtime': path.resolve(workspaceNodeModules, 'react/jsx-dev-runtime.js'),
      'react-dom': path.resolve(workspaceNodeModules, 'react-dom'),
      'react-dom/client': path.resolve(workspaceNodeModules, 'react-dom/client.js'),
      'react-dom/server': path.resolve(workspaceNodeModules, 'react-dom/server.node.js'),
    }
    return config
  },
}

export default nextConfig
