import { ClipboardCheck } from 'lucide-react'

export default function CaseInterventionActions({ caseData, holding, routingStateLoading, interventionStatus, onHold, onManualReviewAction, onSimulate, onRoute, onDiagnose, onDocuments }: any) {
  const pending = caseData.manualReviewStatus === 'pending'
  const action = (title: string, detail: string, onClick: () => void, className: string, disabled = false) => <button type="button" onClick={onClick} disabled={disabled} className={`rounded-xl border px-4 py-3 text-left text-sm disabled:cursor-not-allowed disabled:opacity-50 ${className}`}><p className="font-semibold">{title}</p><p className="mt-1 text-xs opacity-80">{detail}</p></button>
  return <section className="rounded-xl border border-slate-200 bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="flex items-center gap-2 font-semibold text-slate-900"><ClipboardCheck className="h-5 w-5 text-brand-600" />Case intervention actions</h2><p className="mt-1 text-sm text-slate-600">Hold, release, diagnose, simulate, or route this case without leaving the detail page.</p></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${pending ? 'bg-amber-100 text-amber-800' : 'bg-emerald-100 text-emerald-800'}`}>{pending ? 'Manual review' : 'Active'}</span></div>
    {interventionStatus && <div className="mt-4 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{interventionStatus}</div>}
    <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{action('Hold for review', 'Pause routing for ops review.', onHold, 'border-slate-200 bg-slate-50 hover:bg-slate-100', pending)}{action('Release to routing', 'Return held case to routing.', () => onManualReviewAction('release'), 'border-emerald-200 bg-emerald-50 text-emerald-900 hover:bg-emerald-100', !pending || holding)}{action('Simulate routing', 'Preview candidate matching.', onSimulate, 'border-blue-200 bg-blue-50 text-blue-900 hover:bg-blue-100')}{action('Assign attorney', 'Manually route this case.', onRoute, 'border-brand-200 bg-brand-50 text-brand-900 hover:bg-brand-100')}{action('Request info', 'Flag plaintiff follow-up needed.', () => onManualReviewAction('request_info'), 'border-amber-200 bg-amber-50 text-amber-900 hover:bg-amber-100', !pending || holding)}{action('Compliance review', 'Send case to compliance path.', () => onManualReviewAction('compliance'), 'border-violet-200 bg-violet-50 text-violet-900 hover:bg-violet-100', !pending || holding)}{action(routingStateLoading ? 'Diagnosing…' : 'Diagnose routing', 'Inspect intros, waves, and lock state.', onDiagnose, 'border-slate-200 bg-white hover:bg-slate-50', routingStateLoading)}{action('Review documents', 'Open document/OCR queue.', onDocuments, 'border-slate-200 bg-white hover:bg-slate-50')}</div>
  </section>
}
