import AttorneyDebugView from './AttorneyDebugView'
import RoutingStateView from './RoutingStateView'

export default function RouteCaseModal({ attorneys, recommendations, selectedAttorney, attorneyEmail, setSelectedAttorney, setAttorneyEmail, routing, routingTarget, routeSuccess, routeError, invitePrompt, routingState, attorneyDebug, onRoute, onDebug, onVerify, onClose, onDismissInvite }: any) {
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40"><div className="mx-4 max-h-[85vh] w-full max-w-3xl overflow-y-auto rounded-xl bg-white p-6"><h3 className="mb-4 text-lg font-semibold">Route case to attorney</h3>{routeSuccess && <div className="mb-4 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">Routed to {routeSuccess.attorneyName}. Sending you to the routing queue...</div>}
    {recommendations.length > 0 && <div className="mb-5"><p className="mb-2 text-sm font-medium text-slate-700">Recommended shortlist</p><div className="grid grid-cols-1 gap-3 lg:grid-cols-2">{recommendations.map((rec: any) => { const selected = selectedAttorney === rec.attorney.id; const isRouting = routing && routingTarget === rec.attorney.id; const routed = routeSuccess?.attorneyId === rec.attorney.id; return <div key={rec.attorney.id} onClick={() => { setSelectedAttorney(rec.attorney.id); setAttorneyEmail('') }} className={`rounded-lg border p-4 text-left transition ${routed ? 'border-emerald-300 bg-emerald-50/60' : selected ? 'border-brand-500 bg-brand-50' : 'border-slate-200 hover:border-slate-300 hover:bg-slate-50'}`}><p className="text-xs font-semibold uppercase tracking-wide text-brand-700">Rank #{rec.rank}</p><p className="mt-1 font-semibold text-slate-900">{rec.attorney.name}</p><p className="text-sm text-slate-500">{rec.attorney.email || 'No email on file'}</p><p className="mt-2 text-sm text-slate-600">Match {Math.round((rec.matchScore?.overall || 0) * 100)}% · Fit {Math.round((rec.matchScore?.fitScore || 0) * 100)}%</p><div className="mt-4 flex justify-end"><button type="button" onClick={(event) => { event.stopPropagation(); onRoute(rec.attorney.id, { attorneyId: rec.attorney.id, attorneyName: rec.attorney.name }) }} disabled={routing || Boolean(routeSuccess)} className="rounded-lg bg-brand-600 px-3 py-2 text-sm font-medium text-white hover:bg-brand-700 disabled:opacity-50">{routed ? 'Routed' : isRouting ? 'Routing...' : 'Route now'}</button></div></div> })}</div></div>}
    <label className="mb-1 block text-sm font-medium text-slate-700">Recommended attorney or fallback list</label><select value={selectedAttorney} onChange={(event) => { setSelectedAttorney(event.target.value); setAttorneyEmail('') }} className="mb-4 w-full rounded-lg border border-slate-200 px-4 py-2"><option value="">Select attorney</option>{attorneys.map((attorney: any) => <option key={attorney.id} value={attorney.id}>{attorney.name} {attorney.lawFirm?.name ? `(${attorney.lawFirm.name})` : ''} — {attorney.email}</option>)}</select><label className="mb-1 block text-sm font-medium text-slate-700">Or enter attorney email</label><input type="email" value={attorneyEmail} onChange={(event) => { setAttorneyEmail(event.target.value); setSelectedAttorney('') }} placeholder="e.g. aaron.gomez31@lawfirm.com" className="mb-3 w-full rounded-lg border border-slate-200 px-4 py-2" /><p className="mb-3 text-xs text-slate-500">Pick from the ranked shortlist above, use the full attorney list, or type an email override.</p>
    {routingState && <div className="mb-4 max-h-56 overflow-auto rounded-lg bg-slate-50 p-3"><RoutingStateView state={routingState} /></div>}{attorneyDebug && <div className="mb-4 max-h-64 overflow-auto rounded-lg border border-slate-200 bg-slate-50 p-3"><p className="mb-2 text-sm font-semibold text-slate-700">Attorney routing details</p><AttorneyDebugView debug={attorneyDebug} /></div>}{routeError && <div className="mb-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{routeError}</div>}{invitePrompt && <div className="mb-4 rounded-lg border border-blue-200 bg-blue-50 p-3 text-sm text-blue-900"><p className="mb-2">{invitePrompt.message}</p><p className="mb-3 text-xs text-blue-700">We'll create an unclaimed profile and email <span className="break-all font-medium">{invitePrompt.email}</span> a link to join and view this case.</p><div className="flex flex-wrap gap-2"><button onClick={() => onRoute(invitePrompt.email, undefined, true)} disabled={routing} className="rounded-lg bg-blue-600 px-3 py-1.5 text-sm text-white hover:bg-blue-700 disabled:opacity-50">{routing ? 'Inviting…' : 'Invite & route case'}</button><button onClick={onDismissInvite} className="rounded-lg border border-blue-200 px-3 py-1.5 text-sm text-blue-700 hover:bg-blue-100">Cancel</button></div></div>}
    <div className="flex flex-wrap justify-end gap-2"><button onClick={onDebug} disabled={!attorneyEmail.trim()} className="rounded-lg border border-amber-200 px-4 py-2 text-sm text-amber-700 hover:bg-amber-50 disabled:opacity-50">Debug attorney</button><button onClick={() => onVerify(attorneyEmail.trim() || undefined)} className="rounded-lg border border-slate-200 px-4 py-2 text-sm text-slate-600 hover:bg-slate-50">Verify routing</button><button onClick={onClose} className="px-4 py-2 text-slate-600 hover:text-slate-900">Cancel</button><button onClick={() => onRoute()} disabled={(!selectedAttorney && !attorneyEmail.trim()) || routing} className="rounded-lg bg-brand-600 px-4 py-2 text-white hover:bg-brand-700 disabled:opacity-50">{routing ? 'Routing...' : 'Route'}</button></div>
  </div></div>
}
