/**
 * GENERATED FILE — DO NOT EDIT BY HAND.
 *
 * Regenerate with:
 *   cd api && node ../node_modules/tsx/dist/cli.mjs scripts/generate-ca-county-crosswalk.ts
 *
 * Source: U.S. Census Bureau place-by-county reference file (public domain)
 *   https://www2.census.gov/geo/docs/reference/codes2020/place_by_cou/st06_ca_place_by_county2020.txt
 *
 * Covers 1587 distinct California place names across
 * 58 counties, built from 1615 source rows.
 * Includes both incorporated places and census designated places, so
 * unincorporated communities resolve too.
 *
 * Keys are normalized by `normalizeKey()` in ca-counties.ts: lowercased,
 * diacritics and punctuation stripped, whitespace collapsed.
 */

/** Place names that map to exactly one county. */
export const CENSUS_PLACE_TO_COUNTY: Record<string, string> = {
  "acalanes ridge": "Contra Costa",
  "acampo": "San Joaquin",
  "acton": "Los Angeles",
  "adelanto": "San Bernardino",
  "adin": "Modoc",
  "agoura hills": "Los Angeles",
  "agua dulce": "Los Angeles",
  "aguanga": "Riverside",
  "ahwahnee": "Madera",
  "airport": "Stanislaus",
  "alameda": "Alameda",
  "alamo": "Contra Costa",
  "albany": "Alameda",
  "albion": "Mendocino",
  "alderpoint": "Humboldt",
  "alhambra": "Los Angeles",
  "alhambra valley": "Contra Costa",
  "aliso viejo": "Orange",
  "alleghany": "Sierra",
  "allendale": "Solano",
  "allensworth": "Tulare",
  "almanor": "Plumas",
  "alondra park": "Los Angeles",
  "alpaugh": "Tulare",
  "alpine": "San Diego",
  "alpine village": "Alpine",
  "alta": "Placer",
  "altadena": "Los Angeles",
  "alto": "Marin",
  "alturas": "Modoc",
  "alum rock": "Santa Clara",
  "amador city": "Amador",
  "amador pines": "Amador",
  "american canyon": "Napa",
  "amesti": "Santa Cruz",
  "anaheim": "Orange",
  "anchor bay": "Mendocino",
  "anderson": "Shasta",
  "angels": "Calaveras",
  "angwin": "Napa",
  "antelope": "Sacramento",
  "antioch": "Contra Costa",
  "anza": "Riverside",
  "apple valley": "San Bernardino",
  "aptos": "Santa Cruz",
  "aptos hills larkin valley": "Santa Cruz",
  "arbuckle": "Colusa",
  "arcadia": "Los Angeles",
  "arcata": "Humboldt",
  "arden arcade": "Sacramento",
  "armona": "Kings",
  "arnold": "Calaveras",
  "arroyo grande": "San Luis Obispo",
  "artesia": "Los Angeles",
  "artois": "Glenn",
  "arvin": "Kern",
  "ashland": "Alameda",
  "aspen springs": "Mono",
  "atascadero": "San Luis Obispo",
  "atherton": "San Mateo",
  "atwater": "Merced",
  "auberry": "Fresno",
  "auburn": "Placer",
  "auburn lake trails": "El Dorado",
  "august": "San Joaquin",
  "avalon": "Los Angeles",
  "avenal": "Kings",
  "avery": "Calaveras",
  "avila beach": "San Luis Obispo",
  "avocado heights": "Los Angeles",
  "azusa": "Los Angeles",
  "baker": "San Bernardino",
  "bakersfield": "Kern",
  "bakersfield country club": "Kern",
  "baldwin park": "Los Angeles",
  "ballard": "Santa Barbara",
  "ballico": "Merced",
  "bangor": "Butte",
  "banning": "Riverside",
  "barstow": "San Bernardino",
  "bass lake": "Madera",
  "bay point": "Contra Costa",
  "baywood park": "San Mateo",
  "beale afb": "Yuba",
  "bear creek": "Merced",
  "bear valley springs": "Kern",
  "beaumont": "Riverside",
  "beckwourth": "Plumas",
  "belden": "Plumas",
  "bell": "Los Angeles",
  "bell canyon": "Ventura",
  "bell gardens": "Los Angeles",
  "bella vista": "Shasta",
  "bellflower": "Los Angeles",
  "belmont": "San Mateo",
  "belvedere": "Marin",
  "ben lomond": "Santa Cruz",
  "benbow": "Humboldt",
  "bend": "Tehama",
  "benicia": "Solano",
  "benton": "Mono",
  "benton park": "Kern",
  "berkeley": "Alameda",
  "bermuda dunes": "Riverside",
  "berry creek": "Butte",
  "bertsch oceanview": "Del Norte",
  "bethel island": "Contra Costa",
  "beverly hills": "Los Angeles",
  "bieber": "Lassen",
  "big bear city": "San Bernardino",
  "big bear lake": "San Bernardino",
  "big bend": "Shasta",
  "big creek": "Fresno",
  "big lagoon": "Humboldt",
  "big pine": "Inyo",
  "big river": "San Bernardino",
  "biggs": "Butte",
  "biola": "Fresno",
  "bishop": "Inyo",
  "black point green point": "Marin",
  "blackhawk": "Contra Costa",
  "blacklake": "San Luis Obispo",
  "blairsden": "Plumas",
  "bloomfield": "Sonoma",
  "bloomington": "San Bernardino",
  "blue lake": "Humboldt",
  "bluewater": "San Bernardino",
  "blythe": "Riverside",
  "bodega": "Sonoma",
  "bodega bay": "Sonoma",
  "bodfish": "Kern",
  "bolinas": "Marin",
  "bombay beach": "Imperial",
  "bonadelle ranchos": "Madera",
  "bonita": "San Diego",
  "bonny doon": "Santa Cruz",
  "bonsall": "San Diego",
  "boonville": "Mendocino",
  "bootjack": "Mariposa",
  "boron": "Kern",
  "boronda": "Monterey",
  "borrego springs": "San Diego",
  "bostonia": "San Diego",
  "boulder creek": "Santa Cruz",
  "boulevard": "San Diego",
  "bowles": "Fresno",
  "boyes hot springs": "Sonoma",
  "bradbury": "Los Angeles",
  "bradley": "Monterey",
  "brawley": "Imperial",
  "brea": "Orange",
  "brentwood": "Contra Costa",
  "bret harte": "Stanislaus",
  "bridgeport": "Mono",
  "brisbane": "San Mateo",
  "broadmoor": "San Mateo",
  "brookdale": "Santa Cruz",
  "brooks": "Yolo",
  "brooktrails": "Mendocino",
  "buck meadows": "Mariposa",
  "buckhorn": "Amador",
  "bucks lake": "Plumas",
  "buellton": "Santa Barbara",
  "buena park": "Orange",
  "buena vista": "Amador",
  "burbank": "Los Angeles",
  "burlingame": "San Mateo",
  "burney": "Shasta",
  "burnt ranch": "Trinity",
  "butte creek canyon": "Butte",
  "butte meadows": "Butte",
  "butte valley": "Butte",
  "buttonwillow": "Kern",
  "byron": "Contra Costa",
  "bystrom": "Stanislaus",
  "c road": "Plumas",
  "cabazon": "Riverside",
  "calabasas": "Los Angeles",
  "calexico": "Imperial",
  "california city": "Kern",
  "california hot springs": "Tulare",
  "california pines": "Modoc",
  "california polytechnic state university": "San Luis Obispo",
  "calimesa": "Riverside",
  "calipatria": "Imperial",
  "calistoga": "Napa",
  "callender": "San Luis Obispo",
  "calpella": "Mendocino",
  "calpine": "Sierra",
  "calwa": "Fresno",
  "camanche north shore": "Amador",
  "camanche village": "Amador",
  "camarillo": "Ventura",
  "cambria": "San Luis Obispo",
  "cambrian park": "Santa Clara",
  "cameron park": "El Dorado",
  "camino": "El Dorado",
  "camino tassajara": "Contra Costa",
  "camp nelson": "Tulare",
  "camp pendleton mainside": "San Diego",
  "camp pendleton south": "San Diego",
  "campbell": "Santa Clara",
  "campo": "San Diego",
  "camptonville": "Yuba",
  "canby": "Modoc",
  "cantua creek": "Fresno",
  "canyon lake": "Riverside",
  "canyondam": "Plumas",
  "capitola": "Santa Cruz",
  "caribou": "Plumas",
  "carlsbad": "San Diego",
  "carmel by the sea": "Monterey",
  "carmel valley village": "Monterey",
  "carmet": "Sonoma",
  "carmichael": "Sacramento",
  "carnelian bay": "Placer",
  "carpinteria": "Santa Barbara",
  "carrick": "Siskiyou",
  "carson": "Los Angeles",
  "cartago": "Inyo",
  "caruthers": "Fresno",
  "casa conejo": "Ventura",
  "casa de oro mount helix": "San Diego",
  "casa loma": "Kern",
  "casmalia": "Santa Barbara",
  "caspar": "Mendocino",
  "cassel": "Shasta",
  "castaic": "Los Angeles",
  "castella": "Shasta",
  "castle hill": "Contra Costa",
  "castro valley": "Alameda",
  "castroville": "Monterey",
  "cathedral city": "Riverside",
  "catheys valley": "Mariposa",
  "cayucos": "San Luis Obispo",
  "cazadero": "Sonoma",
  "cedar flat": "Placer",
  "cedar ridge": "Tuolumne",
  "cedar slope": "Tulare",
  "cedarville": "Modoc",
  "ceres": "Stanislaus",
  "cerritos": "Los Angeles",
  "chalfant": "Mono",
  "challenge brownsville": "Yuba",
  "channel islands beach": "Ventura",
  "charleston view": "Inyo",
  "charter oak": "Los Angeles",
  "cherokee": "Butte",
  "cherokee strip": "Kern",
  "cherry valley": "Riverside",
  "cherryland": "Alameda",
  "chester": "Plumas",
  "chico": "Butte",
  "chilcoot vinton": "Plumas",
  "china lake acres": "Kern",
  "chinese camp": "Tuolumne",
  "chino": "San Bernardino",
  "chino hills": "San Bernardino",
  "choctaw valley": "Kern",
  "chowchilla": "Madera",
  "chualar": "Monterey",
  "chula vista": "San Diego",
  "citrus": "Los Angeles",
  "citrus heights": "Sacramento",
  "claremont": "Los Angeles",
  "clarksburg": "Yolo",
  "clay": "Sacramento",
  "clayton": "Contra Costa",
  "clear creek": "Lassen",
  "clearlake": "Lake",
  "clearlake oaks": "Lake",
  "clearlake riviera": "Lake",
  "cleone": "Mendocino",
  "clio": "Plumas",
  "clipper mills": "Butte",
  "cloverdale": "Sonoma",
  "clovis": "Fresno",
  "clyde": "Contra Costa",
  "coachella": "Riverside",
  "coalinga": "Fresno",
  "coarsegold": "Madera",
  "cobb": "Lake",
  "coffee creek": "Trinity",
  "cohasset": "Butte",
  "coleville": "Mono",
  "colfax": "Placer",
  "college city": "Colusa",
  "collierville": "San Joaquin",
  "colma": "San Mateo",
  "coloma": "El Dorado",
  "colton": "San Bernardino",
  "columbia": "Tuolumne",
  "colusa": "Colusa",
  "commerce": "Los Angeles",
  "comptche": "Mendocino",
  "compton": "Los Angeles",
  "concord": "Contra Costa",
  "concow": "Butte",
  "contra costa centre": "Contra Costa",
  "copperopolis": "Calaveras",
  "corcoran": "Kings",
  "corning": "Tehama",
  "corona": "Riverside",
  "coronado": "San Diego",
  "coronita": "Riverside",
  "corralitos": "Santa Cruz",
  "corte madera": "Marin",
  "costa mesa": "Orange",
  "cotati": "Sonoma",
  "coto de caza": "Orange",
  "coulterville": "Mariposa",
  "country club": "San Joaquin",
  "courtland": "Sacramento",
  "covelo": "Mendocino",
  "covina": "Los Angeles",
  "cowan": "Stanislaus",
  "crane creek": "Mariposa",
  "crescent city": "Del Norte",
  "crescent mills": "Plumas",
  "cressey": "Merced",
  "crest": "San Diego",
  "crestline": "San Bernardino",
  "creston": "San Luis Obispo",
  "crockett": "Contra Costa",
  "cromberg": "Plumas",
  "crowley lake": "Mono",
  "crows landing": "Stanislaus",
  "cudahy": "Los Angeles",
  "culver city": "Los Angeles",
  "cupertino": "Santa Clara",
  "cutler": "Tulare",
  "cutten": "Humboldt",
  "cuyama": "Santa Barbara",
  "cypress": "Orange",
  "dales": "Tehama",
  "daly city": "San Mateo",
  "dana point": "Orange",
  "danville": "Contra Costa",
  "daphnedale park": "Modoc",
  "darwin": "Inyo",
  "davenport": "Santa Cruz",
  "davis": "Yolo",
  "day valley": "Santa Cruz",
  "deer park": "Napa",
  "del aire": "Los Angeles",
  "del dios": "San Diego",
  "del mar": "San Diego",
  "del monte forest": "Monterey",
  "del rey": "Fresno",
  "del rey oaks": "Monterey",
  "del rio": "Stanislaus",
  "delano": "Kern",
  "delft colony": "Tulare",
  "delhi": "Merced",
  "delleker": "Plumas",
  "denair": "Stanislaus",
  "derby acres": "Kern",
  "descanso": "San Diego",
  "desert center": "Riverside",
  "desert edge": "Riverside",
  "desert hot springs": "Riverside",
  "desert palms": "Riverside",
  "desert shores": "Imperial",
  "desert view highlands": "Los Angeles",
  "di giorgio": "Kern",
  "diablo": "Contra Costa",
  "diablo grande": "Stanislaus",
  "diamond bar": "Los Angeles",
  "diamond springs": "El Dorado",
  "dillon beach": "Marin",
  "dinuba": "Tulare",
  "discovery bay": "Contra Costa",
  "dixon": "Solano",
  "dixon lane meadowcreek": "Inyo",
  "dobbins": "Yuba",
  "dogtown": "San Joaquin",
  "dollar point": "Placer",
  "dorrington": "Calaveras",
  "dorris": "Siskiyou",
  "dos palos": "Merced",
  "dos palos y": "Merced",
  "douglas city": "Trinity",
  "downey": "Los Angeles",
  "downieville": "Sierra",
  "doyle": "Lassen",
  "drytown": "Amador",
  "duarte": "Los Angeles",
  "dublin": "Alameda",
  "ducor": "Tulare",
  "dunnigan": "Yolo",
  "dunsmuir": "Siskiyou",
  "durham": "Butte",
  "dustin acres": "Kern",
  "dutch flat": "Placer",
  "eagleville": "Modoc",
  "earlimart": "Tulare",
  "east bakersfield": "Kern",
  "east foothills": "Santa Clara",
  "east hemet": "Riverside",
  "east los angeles": "Los Angeles",
  "east nicolaus": "Sutter",
  "east niles": "Kern",
  "east oakdale": "Stanislaus",
  "east orosi": "Tulare",
  "east palo alto": "San Mateo",
  "east pasadena": "Los Angeles",
  "east porterville": "Tulare",
  "east quincy": "Plumas",
  "east rancho dominguez": "Los Angeles",
  "east richmond heights": "Contra Costa",
  "east san gabriel": "Los Angeles",
  "east shore": "Plumas",
  "east sonora": "Tuolumne",
  "east tulare villa": "Tulare",
  "east whittier": "Los Angeles",
  "eastern goleta valley": "Santa Barbara",
  "easton": "Fresno",
  "eastvale": "Riverside",
  "edgewood": "Siskiyou",
  "edison": "Kern",
  "edmundson acres": "Kern",
  "edna": "San Luis Obispo",
  "edwards afb": "Kern",
  "el adobe": "Kern",
  "el cajon": "San Diego",
  "el centro": "Imperial",
  "el centro naval air facility": "Imperial",
  "el cerrito": "Contra Costa",
  "el dorado hills": "El Dorado",
  "el granada": "San Mateo",
  "el macero": "Yolo",
  "el monte": "Los Angeles",
  "el monte mobile village": "Tulare",
  "el nido": "Merced",
  "el paso de robles paso robles": "San Luis Obispo",
  "el portal": "Mariposa",
  "el rancho": "Tulare",
  "el rio": "Ventura",
  "el segundo": "Los Angeles",
  "el verano": "Sonoma",
  "eldridge": "Sonoma",
  "elfin forest": "San Diego",
  "elizabeth lake": "Los Angeles",
  "elk creek": "Glenn",
  "elk grove": "Sacramento",
  "elkhorn": "Monterey",
  "elmira": "Solano",
  "elverta": "Sacramento",
  "emerald lake hills": "San Mateo",
  "emeryville": "Alameda",
  "empire": "Stanislaus",
  "encinitas": "San Diego",
  "escalon": "San Joaquin",
  "escondido": "San Diego",
  "esparto": "Yolo",
  "etna": "Siskiyou",
  "eucalyptus hills": "San Diego",
  "eureka": "Humboldt",
  "exeter": "Tulare",
  "fair oaks": "Sacramento",
  "fairbanks ranch": "San Diego",
  "fairfax": "Marin",
  "fairfield": "Solano",
  "fairhaven": "Humboldt",
  "fairmead": "Madera",
  "fairview": "Alameda",
  "fall river mills": "Shasta",
  "fallbrook": "San Diego",
  "farmersville": "Tulare",
  "farmington": "San Joaquin",
  "fellows": "Kern",
  "felton": "Santa Cruz",
  "ferndale": "Humboldt",
  "fetters hot springs agua caliente": "Sonoma",
  "fiddletown": "Amador",
  "fieldbrook": "Humboldt",
  "fields landing": "Humboldt",
  "fillmore": "Ventura",
  "firebaugh": "Fresno",
  "fish camp": "Mariposa",
  "florence graham": "Los Angeles",
  "florin": "Sacramento",
  "floriston": "Nevada",
  "flournoy": "Tehama",
  "folsom": "Sacramento",
  "fontana": "San Bernardino",
  "foothill farms": "Sacramento",
  "forbestown": "Butte",
  "ford city": "Kern",
  "forest meadows": "Calaveras",
  "forest ranch": "Butte",
  "foresthill": "Placer",
  "forestville": "Sonoma",
  "fort bidwell": "Modoc",
  "fort bragg": "Mendocino",
  "fort dick": "Del Norte",
  "fort hunter liggett": "Monterey",
  "fort irwin": "San Bernardino",
  "fort jones": "Siskiyou",
  "fort washington": "Fresno",
  "fortuna": "Humboldt",
  "foster city": "San Mateo",
  "fountain valley": "Orange",
  "fowler": "Fresno",
  "frazier park": "Kern",
  "freedom": "Santa Cruz",
  "freeport": "Sacramento",
  "fremont": "Alameda",
  "french camp": "San Joaquin",
  "french gulch": "Shasta",
  "french valley": "Riverside",
  "fresno": "Fresno",
  "friant": "Fresno",
  "fruitdale": "Santa Clara",
  "fruitridge pocket": "Sacramento",
  "fuller acres": "Kern",
  "fullerton": "Orange",
  "fulton": "Sonoma",
  "furnace creek": "Inyo",
  "galt": "Sacramento",
  "garberville": "Humboldt",
  "garden acres": "San Joaquin",
  "garden farms": "San Luis Obispo",
  "garden grove": "Orange",
  "gardena": "Los Angeles",
  "garey": "Santa Barbara",
  "garnet": "Riverside",
  "gasquet": "Del Norte",
  "gazelle": "Siskiyou",
  "georgetown": "El Dorado",
  "gerber": "Tehama",
  "geyserville": "Sonoma",
  "gilroy": "Santa Clara",
  "glen ellen": "Sonoma",
  "glendale": "Los Angeles",
  "glendora": "Los Angeles",
  "glennville": "Kern",
  "gold mountain": "Plumas",
  "gold river": "Sacramento",
  "golden hills": "Kern",
  "goleta": "Santa Barbara",
  "gonzales": "Monterey",
  "good hope": "Riverside",
  "goodmanville": "Kern",
  "goodyears bar": "Sierra",
  "goshen": "Tulare",
  "graeagle": "Plumas",
  "grand terrace": "San Bernardino",
  "grangeville": "Kings",
  "granite bay": "Placer",
  "granite hills": "San Diego",
  "graniteville": "Nevada",
  "grass valley": "Nevada",
  "graton": "Sonoma",
  "grayson": "Stanislaus",
  "greeley hill": "Mariposa",
  "green acres": "Riverside",
  "greenacres": "Kern",
  "greenfield": "Monterey",
  "greenhorn": "Plumas",
  "greenview": "Siskiyou",
  "greenville": "Plumas",
  "grenada": "Siskiyou",
  "gridley": "Butte",
  "grimes": "Colusa",
  "grizzly flats": "El Dorado",
  "groveland": "Tuolumne",
  "grover beach": "San Luis Obispo",
  "guadalupe": "Santa Barbara",
  "guerneville": "Sonoma",
  "guinda": "Yolo",
  "gustine": "Merced",
  "hacienda heights": "Los Angeles",
  "half moon bay": "San Mateo",
  "hamilton branch": "Plumas",
  "hamilton city": "Glenn",
  "hanford": "Kings",
  "happy camp": "Siskiyou",
  "happy valley": "Shasta",
  "harbison canyon": "San Diego",
  "hardwick": "Kings",
  "harmony grove": "San Diego",
  "hartland": "Tulare",
  "hartley": "Solano",
  "hasley canyon": "Los Angeles",
  "hat creek": "Shasta",
  "hawaiian gardens": "Los Angeles",
  "hawthorne": "Los Angeles",
  "hayfork": "Trinity",
  "hayward": "Alameda",
  "healdsburg": "Sonoma",
  "heber": "Imperial",
  "hemet": "Riverside",
  "herald": "Sacramento",
  "hercules": "Contra Costa",
  "herlong": "Lassen",
  "hermosa beach": "Los Angeles",
  "hesperia": "San Bernardino",
  "hickman": "Stanislaus",
  "hidden hills": "Los Angeles",
  "hidden meadows": "San Diego",
  "hidden valley lake": "Lake",
  "highgrove": "Riverside",
  "highland": "San Bernardino",
  "highlands": "San Mateo",
  "hillcrest": "Kern",
  "hillsborough": "San Mateo",
  "hilmar irwin": "Merced",
  "hiouchi": "Del Norte",
  "hollister": "San Benito",
  "holtville": "Imperial",
  "home garden": "Kings",
  "home gardens": "Riverside",
  "homeland": "Riverside",
  "homestead valley": "San Bernardino",
  "homewood canyon": "Inyo",
  "honcut": "Butte",
  "hood": "Sacramento",
  "hoopa": "Humboldt",
  "hopland": "Mendocino",
  "hornbrook": "Siskiyou",
  "hornitos": "Mariposa",
  "hughson": "Stanislaus",
  "humboldt hill": "Humboldt",
  "huntington beach": "Orange",
  "huntington park": "Los Angeles",
  "huron": "Fresno",
  "hyampom": "Trinity",
  "hydesville": "Humboldt",
  "hypericum": "Tulare",
  "idlewild": "Tulare",
  "idyllwild pine cove": "Riverside",
  "igo": "Shasta",
  "imperial": "Imperial",
  "imperial beach": "San Diego",
  "independence": "Inyo",
  "indian falls": "Plumas",
  "indian wells": "Riverside",
  "indianola": "Humboldt",
  "indio": "Riverside",
  "indio hills": "Riverside",
  "industry": "Los Angeles",
  "inglewood": "Los Angeles",
  "interlaken": "Santa Cruz",
  "inverness": "Marin",
  "inyokern": "Kern",
  "ione": "Amador",
  "iron horse": "Plumas",
  "irvine": "Orange",
  "irwindale": "Los Angeles",
  "isla vista": "Santa Barbara",
  "isleton": "Sacramento",
  "ivanhoe": "Tulare",
  "jackson": "Amador",
  "jacumba": "San Diego",
  "jamestown": "Tuolumne",
  "jamul": "San Diego",
  "janesville": "Lassen",
  "jenner": "Sonoma",
  "johannesburg": "Kern",
  "johnson park": "Shasta",
  "johnstonville": "Lassen",
  "johnsville": "Plumas",
  "jones valley": "Shasta",
  "joshua tree": "San Bernardino",
  "jovista": "Tulare",
  "julian": "San Diego",
  "junction city": "Trinity",
  "june lake": "Mono",
  "jurupa valley": "Riverside",
  "keddie": "Plumas",
  "keeler": "Inyo",
  "keene": "Kern",
  "kelly ridge": "Butte",
  "kelseyville": "Lake",
  "kennedy": "San Joaquin",
  "kennedy meadows": "Tulare",
  "kensington": "Contra Costa",
  "kentfield": "Marin",
  "kenwood": "Sonoma",
  "kep el": "Humboldt",
  "kerman": "Fresno",
  "kernville": "Kern",
  "keswick": "Shasta",
  "kettleman city": "Kings",
  "keyes": "Stanislaus",
  "king city": "Monterey",
  "kings beach": "Placer",
  "kingsburg": "Fresno",
  "klamath": "Del Norte",
  "knights ferry": "Stanislaus",
  "knights landing": "Yolo",
  "knightsen": "Contra Costa",
  "la canada flintridge": "Los Angeles",
  "la crescenta montrose": "Los Angeles",
  "la cresta": "Kern",
  "la grange": "Stanislaus",
  "la habra": "Orange",
  "la habra heights": "Los Angeles",
  "la honda": "San Mateo",
  "la mesa": "San Diego",
  "la mirada": "Los Angeles",
  "la palma": "Orange",
  "la porte": "Plumas",
  "la presa": "San Diego",
  "la puente": "Los Angeles",
  "la quinta": "Riverside",
  "la riviera": "Sacramento",
  "la selva beach": "Santa Cruz",
  "la verne": "Los Angeles",
  "la vina": "Madera",
  "ladera": "San Mateo",
  "ladera heights": "Los Angeles",
  "ladera ranch": "Orange",
  "lafayette": "Contra Costa",
  "laguna beach": "Orange",
  "laguna hills": "Orange",
  "laguna niguel": "Orange",
  "laguna woods": "Orange",
  "lagunitas forest knolls": "Marin",
  "lake almanor country club": "Plumas",
  "lake almanor peninsula": "Plumas",
  "lake almanor west": "Plumas",
  "lake arrowhead": "San Bernardino",
  "lake california": "Tehama",
  "lake city": "Modoc",
  "lake davis": "Plumas",
  "lake don pedro": "Mariposa",
  "lake elsinore": "Riverside",
  "lake forest": "Orange",
  "lake hughes": "Los Angeles",
  "lake isabella": "Kern",
  "lake los angeles": "Los Angeles",
  "lake mathews": "Riverside",
  "lake nacimiento": "San Luis Obispo",
  "lake of the pines": "Nevada",
  "lake of the woods": "Kern",
  "lake riverside": "Riverside",
  "lake san marcos": "San Diego",
  "lake shastina": "Siskiyou",
  "lake sherwood": "Ventura",
  "lake wildwood": "Nevada",
  "lakehead": "Shasta",
  "lakeland village": "Riverside",
  "lakeport": "Lake",
  "lakeview": "Riverside",
  "lakewood": "Los Angeles",
  "lamont": "Kern",
  "lanare": "Fresno",
  "lancaster": "Los Angeles",
  "larkfield wikiup": "Sonoma",
  "larkspur": "Marin",
  "las lomas": "Monterey",
  "lathrop": "San Joaquin",
  "laton": "Fresno",
  "lawndale": "Los Angeles",
  "laytonville": "Mendocino",
  "le grand": "Merced",
  "lebec": "Kern",
  "lee vining": "Mono",
  "leggett": "Mendocino",
  "lemon cove": "Tulare",
  "lemon grove": "San Diego",
  "lemon hill": "Sacramento",
  "lemoore": "Kings",
  "lemoore station": "Kings",
  "lennox": "Los Angeles",
  "lenwood": "San Bernardino",
  "leona valley": "Los Angeles",
  "lewiston": "Trinity",
  "lexington hills": "Santa Clara",
  "likely": "Modoc",
  "lincoln": "Placer",
  "lincoln village": "San Joaquin",
  "linda": "Yuba",
  "lindcove": "Tulare",
  "linden": "San Joaquin",
  "lindsay": "Tulare",
  "linnell camp": "Tulare",
  "litchfield": "Lassen",
  "little grass valley": "Plumas",
  "little river": "Mendocino",
  "little valley": "Lassen",
  "littlerock": "Los Angeles",
  "live oak": "Sutter",
  "livermore": "Alameda",
  "livingston": "Merced",
  "lockeford": "San Joaquin",
  "lodi": "San Joaquin",
  "lodoga": "Colusa",
  "loleta": "Humboldt",
  "loma linda": "San Bernardino",
  "loma mar": "San Mateo",
  "loma rica": "Yuba",
  "lomita": "Los Angeles",
  "lompico": "Santa Cruz",
  "lompoc": "Santa Barbara",
  "london": "Tulare",
  "lone pine": "Inyo",
  "long barn": "Tuolumne",
  "long beach": "Los Angeles",
  "lookout": "Modoc",
  "loomis": "Placer",
  "los alamitos": "Orange",
  "los alamos": "Santa Barbara",
  "los altos": "Santa Clara",
  "los altos hills": "Santa Clara",
  "los angeles": "Los Angeles",
  "los banos": "Merced",
  "los berros": "San Luis Obispo",
  "los gatos": "Santa Clara",
  "los molinos": "Tehama",
  "los olivos": "Santa Barbara",
  "los osos": "San Luis Obispo",
  "los ranchos": "San Luis Obispo",
  "lost hills": "Kern",
  "lower lake": "Lake",
  "loyalton": "Sierra",
  "loyola": "Santa Clara",
  "lucas valley marinwood": "Marin",
  "lucerne": "Lake",
  "lucerne valley": "San Bernardino",
  "lynwood": "Los Angeles",
  "lytle creek": "San Bernardino",
  "mabie": "Plumas",
  "macdoel": "Siskiyou",
  "mad river": "Trinity",
  "madeline": "Lassen",
  "madera": "Madera",
  "madera acres": "Madera",
  "madera ranchos": "Madera",
  "madison": "Yolo",
  "magalia": "Butte",
  "malaga": "Fresno",
  "malibu": "Los Angeles",
  "mammoth lakes": "Mono",
  "manchester": "Mendocino",
  "manhattan beach": "Los Angeles",
  "manila": "Humboldt",
  "manteca": "San Joaquin",
  "manton": "Tehama",
  "march arb": "Riverside",
  "maricopa": "Kern",
  "marin city": "Marin",
  "marina": "Monterey",
  "marina del rey": "Los Angeles",
  "mariposa": "Mariposa",
  "markleeville": "Alpine",
  "martell": "Amador",
  "martinez": "Contra Costa",
  "marysville": "Yuba",
  "matheny": "Tulare",
  "mather": "Sacramento",
  "maxwell": "Colusa",
  "mayfair": "Fresno",
  "mayflower village": "Los Angeles",
  "maywood": "Los Angeles",
  "mcarthur": "Shasta",
  "mcclellan park": "Sacramento",
  "mcclenney tract": "Tulare",
  "mccloud": "Siskiyou",
  "mcfarland": "Kern",
  "mcgee creek": "Mono",
  "mckinleyville": "Humboldt",
  "mckittrick": "Kern",
  "mcswain": "Merced",
  "mead valley": "Riverside",
  "meadow valley": "Plumas",
  "meadow vista": "Placer",
  "meadowbrook": "Riverside",
  "mecca": "Riverside",
  "meiners oaks": "Ventura",
  "mendocino": "Mendocino",
  "mendota": "Fresno",
  "menifee": "Riverside",
  "menlo park": "San Mateo",
  "mentone": "San Bernardino",
  "merced": "Merced",
  "meridian": "Sutter",
  "mesa": "Inyo",
  "mesa verde": "Riverside",
  "mesa vista": "Alpine",
  "mettler": "Kern",
  "mexican colony": "Kern",
  "meyers": "El Dorado",
  "mi wuk village": "Tuolumne",
  "middletown": "Lake",
  "midpines": "Mariposa",
  "midway city": "Orange",
  "milford": "Lassen",
  "mill valley": "Marin",
  "millbrae": "San Mateo",
  "millerton": "Fresno",
  "millville": "Shasta",
  "milpitas": "Santa Clara",
  "mineral": "Tehama",
  "minkler": "Fresno",
  "mira monte": "Ventura",
  "miranda": "Humboldt",
  "mission canyon": "Santa Barbara",
  "mission hills": "Santa Barbara",
  "mission viejo": "Orange",
  "modesto": "Stanislaus",
  "modjeska": "Orange",
  "mohawk vista": "Plumas",
  "mojave": "Kern",
  "mokelumne hill": "Calaveras",
  "monmouth": "Fresno",
  "mono city": "Mono",
  "mono vista": "Tuolumne",
  "monrovia": "Los Angeles",
  "monson": "Tulare",
  "montague": "Siskiyou",
  "montalvin manor": "Contra Costa",
  "montara": "San Mateo",
  "montclair": "San Bernardino",
  "monte rio": "Sonoma",
  "monte sereno": "Santa Clara",
  "montebello": "Los Angeles",
  "montecito": "Santa Barbara",
  "monterey": "Monterey",
  "monterey park": "Los Angeles",
  "monterey park tract": "Stanislaus",
  "montgomery creek": "Shasta",
  "monument hills": "Yolo",
  "moorpark": "Ventura",
  "morada": "San Joaquin",
  "moraga": "Contra Costa",
  "moreno valley": "Riverside",
  "morgan hill": "Santa Clara",
  "morongo valley": "San Bernardino",
  "morro bay": "San Luis Obispo",
  "moskowite corner": "Napa",
  "moss beach": "San Mateo",
  "moss landing": "Monterey",
  "mount hebron": "Siskiyou",
  "mount hermon": "Santa Cruz",
  "mount laguna": "San Diego",
  "mount shasta": "Siskiyou",
  "mountain center": "Riverside",
  "mountain gate": "Shasta",
  "mountain house": "San Joaquin",
  "mountain meadows": "Kern",
  "mountain mesa": "Kern",
  "mountain ranch": "Calaveras",
  "mountain view": "Santa Clara",
  "mountain view acres": "San Bernardino",
  "mt bullion": "Mariposa",
  "muir beach": "Marin",
  "murphys": "Calaveras",
  "murrieta": "Riverside",
  "muscoy": "San Bernardino",
  "myers flat": "Humboldt",
  "myrtletown": "Humboldt",
  "napa": "Napa",
  "national city": "San Diego",
  "needles": "San Bernardino",
  "nevada city": "Nevada",
  "new cuyama": "Santa Barbara",
  "new pine creek": "Modoc",
  "newark": "Alameda",
  "newcastle": "Placer",
  "newell": "Modoc",
  "newman": "Stanislaus",
  "newport beach": "Orange",
  "nicasio": "Marin",
  "nice": "Lake",
  "nicolaus": "Sutter",
  "niland": "Imperial",
  "nipinnawasee": "Madera",
  "nipomo": "San Luis Obispo",
  "norco": "Riverside",
  "nord": "Butte",
  "norris canyon": "Contra Costa",
  "north auburn": "Placer",
  "north edwards": "Kern",
  "north el monte": "Los Angeles",
  "north fair oaks": "San Mateo",
  "north fork": "Madera",
  "north gate": "Contra Costa",
  "north highlands": "Sacramento",
  "north lakeport": "Lake",
  "north richmond": "Contra Costa",
  "north san juan": "Nevada",
  "north shore": "Riverside",
  "north tustin": "Orange",
  "norwalk": "Los Angeles",
  "novato": "Marin",
  "nubieber": "Lassen",
  "nuevo": "Riverside",
  "oak glen": "San Bernardino",
  "oak hills": "San Bernardino",
  "oak park": "Ventura",
  "oak run": "Shasta",
  "oak shores": "San Luis Obispo",
  "oak view": "Ventura",
  "oakdale": "Stanislaus",
  "oakhurst": "Madera",
  "oakland": "Alameda",
  "oakley": "Contra Costa",
  "oakville": "Napa",
  "oasis": "Riverside",
  "occidental": "Sonoma",
  "oceano": "San Luis Obispo",
  "oceanside": "San Diego",
  "ocotillo": "Imperial",
  "oildale": "Kern",
  "ojai": "Ventura",
  "olancha": "Inyo",
  "old fig garden": "Fresno",
  "old river": "Kern",
  "old station": "Shasta",
  "old stine": "Kern",
  "olde stockdale": "Kern",
  "olivehurst": "Yuba",
  "ono": "Shasta",
  "ontario": "San Bernardino",
  "onyx": "Kern",
  "orange": "Orange",
  "orange blossom": "Stanislaus",
  "orange cove": "Fresno",
  "orangevale": "Sacramento",
  "orcutt": "Santa Barbara",
  "orick": "Humboldt",
  "orinda": "Contra Costa",
  "orland": "Glenn",
  "orosi": "Tulare",
  "oroville": "Butte",
  "oroville east": "Butte",
  "oxnard": "Ventura",
  "pacheco": "Contra Costa",
  "pacific grove": "Monterey",
  "pacifica": "San Mateo",
  "pajaro": "Monterey",
  "pajaro dunes": "Santa Cruz",
  "pala": "San Diego",
  "palermo": "Butte",
  "palm desert": "Riverside",
  "palm springs": "Riverside",
  "palmdale": "Los Angeles",
  "palo alto": "Santa Clara",
  "palo cedro": "Shasta",
  "palo verde": "Imperial",
  "palos verdes estates": "Los Angeles",
  "panorama heights": "Tulare",
  "paradise": "Butte",
  "paradise park": "Santa Cruz",
  "paramount": "Los Angeles",
  "parklawn": "Stanislaus",
  "parksdale": "Madera",
  "parkway": "Sacramento",
  "parkwood": "Madera",
  "parlier": "Fresno",
  "pasadena": "Los Angeles",
  "pasatiempo": "Santa Cruz",
  "paskenta": "Tehama",
  "patterson": "Stanislaus",
  "patterson tract": "Tulare",
  "patton village": "Lassen",
  "paxton": "Plumas",
  "paynes creek": "Tehama",
  "pearsonville": "Inyo",
  "penn valley": "Nevada",
  "penngrove": "Sonoma",
  "penryn": "Placer",
  "pepperdine university": "Los Angeles",
  "perris": "Riverside",
  "pescadero": "San Mateo",
  "petaluma": "Sonoma",
  "petaluma center": "Sonoma",
  "peters": "San Joaquin",
  "phelan": "San Bernardino",
  "phillipsville": "Humboldt",
  "philo": "Mendocino",
  "phoenix lake": "Tuolumne",
  "pico rivera": "Los Angeles",
  "piedmont": "Alameda",
  "pierpoint": "Tulare",
  "pike": "Sierra",
  "pine canyon": "Monterey",
  "pine flat": "Tulare",
  "pine grove": "Amador",
  "pine hills": "Humboldt",
  "pine mountain club": "Kern",
  "pine mountain lake": "Tuolumne",
  "pine valley": "San Diego",
  "pinole": "Contra Costa",
  "pinon hills": "San Bernardino",
  "pioneer": "Amador",
  "piru": "Ventura",
  "pismo beach": "San Luis Obispo",
  "pittsburg": "Contra Costa",
  "pixley": "Tulare",
  "placentia": "Orange",
  "placerville": "El Dorado",
  "plainview": "Tulare",
  "planada": "Merced",
  "platina": "Shasta",
  "pleasant hill": "Contra Costa",
  "pleasanton": "Alameda",
  "pleasure point": "Santa Cruz",
  "plumas eureka": "Plumas",
  "plumas lake": "Yuba",
  "plymouth": "Amador",
  "point arena": "Mendocino",
  "point reyes station": "Marin",
  "pollock pines": "El Dorado",
  "pomona": "Los Angeles",
  "ponderosa": "Tulare",
  "poplar cotton center": "Tulare",
  "port costa": "Contra Costa",
  "port hueneme": "Ventura",
  "porterville": "Tulare",
  "portola": "Plumas",
  "portola valley": "San Mateo",
  "posey": "Tulare",
  "poso park": "Tulare",
  "post mountain": "Trinity",
  "potomac park": "Kern",
  "potrero": "San Diego",
  "potter valley": "Mendocino",
  "poway": "San Diego",
  "prattville": "Plumas",
  "princeton": "Colusa",
  "proberta": "Tehama",
  "prunedale": "Monterey",
  "pumpkin center": "Kern",
  "quartz hill": "Los Angeles",
  "quincy": "Plumas",
  "rackerby": "Butte",
  "rail road flat": "Calaveras",
  "rainbow": "San Diego",
  "raisin city": "Fresno",
  "ramona": "San Diego",
  "rancho calaveras": "Calaveras",
  "rancho cordova": "Sacramento",
  "rancho cucamonga": "San Bernardino",
  "rancho mirage": "Riverside",
  "rancho mission viejo": "Orange",
  "rancho murieta": "Sacramento",
  "rancho palos verdes": "Los Angeles",
  "rancho san diego": "San Diego",
  "rancho santa fe": "San Diego",
  "rancho santa margarita": "Orange",
  "rancho tehama reserve": "Tehama",
  "randsburg": "Kern",
  "red bluff": "Tehama",
  "red corral": "Amador",
  "redcrest": "Humboldt",
  "redding": "Shasta",
  "redlands": "San Bernardino",
  "redondo beach": "Los Angeles",
  "redway": "Humboldt",
  "redwood city": "San Mateo",
  "redwood valley": "Mendocino",
  "reedley": "Fresno",
  "reliez valley": "Contra Costa",
  "rexland acres": "Kern",
  "rialto": "San Bernardino",
  "richfield": "Tehama",
  "richgrove": "Tulare",
  "richmond": "Contra Costa",
  "richvale": "Butte",
  "ridgecrest": "Kern",
  "ridgecrest heights": "Kern",
  "ridgemark": "San Benito",
  "rio del mar": "Santa Cruz",
  "rio dell": "Humboldt",
  "rio linda": "Sacramento",
  "rio oso": "Sutter",
  "rio vista": "Solano",
  "ripley": "Riverside",
  "ripon": "San Joaquin",
  "river pines": "Amador",
  "riverbank": "Stanislaus",
  "riverdale": "Fresno",
  "riverdale park": "Stanislaus",
  "rivergrove": "Kern",
  "riverside": "Riverside",
  "robbins": "Sutter",
  "robinson mill": "Butte",
  "rocklin": "Placer",
  "rodeo": "Contra Costa",
  "rodriguez camp": "Tulare",
  "rohnert park": "Sonoma",
  "rolling hills": "Los Angeles",
  "rolling hills estates": "Los Angeles",
  "rollingwood": "Contra Costa",
  "romoland": "Riverside",
  "rosamond": "Kern",
  "rose hills": "Los Angeles",
  "rosedale": "Kern",
  "rosemead": "Los Angeles",
  "rosemont": "Sacramento",
  "roseville": "Placer",
  "ross": "Marin",
  "rossmoor": "Orange",
  "rough and ready": "Nevada",
  "round mountain": "Shasta",
  "round valley": "Inyo",
  "rouse": "Stanislaus",
  "rowland heights": "Los Angeles",
  "rumsey": "Yolo",
  "running springs": "San Bernardino",
  "ruth": "Trinity",
  "rutherford": "Napa",
  "sacramento": "Sacramento",
  "sage": "Riverside",
  "salida": "Stanislaus",
  "salinas": "Monterey",
  "salmon creek": "Sonoma",
  "salton city": "Imperial",
  "salton sea beach": "Imperial",
  "salyer": "Trinity",
  "samoa": "Humboldt",
  "san andreas": "Calaveras",
  "san anselmo": "Marin",
  "san antonio heights": "San Bernardino",
  "san ardo": "Monterey",
  "san bernardino": "San Bernardino",
  "san bruno": "San Mateo",
  "san buenaventura ventura": "Ventura",
  "san carlos": "San Mateo",
  "san clemente": "Orange",
  "san diego": "San Diego",
  "san diego country estates": "San Diego",
  "san dimas": "Los Angeles",
  "san fernando": "Los Angeles",
  "san francisco": "San Francisco",
  "san gabriel": "Los Angeles",
  "san geronimo": "Marin",
  "san jacinto": "Riverside",
  "san joaquin": "Fresno",
  "san jose": "Santa Clara",
  "san juan bautista": "San Benito",
  "san juan capistrano": "Orange",
  "san leandro": "Alameda",
  "san lorenzo": "Alameda",
  "san lucas": "Monterey",
  "san luis obispo": "San Luis Obispo",
  "san marcos": "San Diego",
  "san marino": "Los Angeles",
  "san martin": "Santa Clara",
  "san mateo": "San Mateo",
  "san pablo": "Contra Costa",
  "san pasqual": "Los Angeles",
  "san rafael": "Marin",
  "san ramon": "Contra Costa",
  "san simeon": "San Luis Obispo",
  "sand city": "Monterey",
  "sanger": "Fresno",
  "santa ana": "Orange",
  "santa barbara": "Santa Barbara",
  "santa clara": "Santa Clara",
  "santa clarita": "Los Angeles",
  "santa cruz": "Santa Cruz",
  "santa fe springs": "Los Angeles",
  "santa margarita": "San Luis Obispo",
  "santa maria": "Santa Barbara",
  "santa monica": "Los Angeles",
  "santa nella": "Merced",
  "santa paula": "Ventura",
  "santa rosa": "Sonoma",
  "santa rosa valley": "Ventura",
  "santa susana": "Ventura",
  "santa venetia": "Marin",
  "santa ynez": "Santa Barbara",
  "santee": "San Diego",
  "saranap": "Contra Costa",
  "saratoga": "Santa Clara",
  "saticoy": "Ventura",
  "sattley": "Sierra",
  "sausalito": "Marin",
  "scotia": "Humboldt",
  "scotts valley": "Santa Cruz",
  "sea ranch": "Sonoma",
  "seacliff": "Santa Cruz",
  "seal beach": "Orange",
  "searles valley": "San Bernardino",
  "seaside": "Monterey",
  "sebastopol": "Sonoma",
  "seeley": "Imperial",
  "selma": "Fresno",
  "sequoia crest": "Tulare",
  "sereno del mar": "Sonoma",
  "seville": "Tulare",
  "shafter": "Kern",
  "shandon": "San Luis Obispo",
  "shasta": "Shasta",
  "shasta lake": "Shasta",
  "shaver lake": "Fresno",
  "shell ridge": "Contra Costa",
  "shelter cove": "Humboldt",
  "sheridan": "Placer",
  "shingle springs": "El Dorado",
  "shingletown": "Shasta",
  "shoshone": "Inyo",
  "sierra brooks": "Sierra",
  "sierra city": "Sierra",
  "sierra madre": "Los Angeles",
  "sierra village": "Tuolumne",
  "sierraville": "Sierra",
  "signal hill": "Los Angeles",
  "silver city": "Tulare",
  "silver lakes": "San Bernardino",
  "silverado": "Orange",
  "silverado resort": "Napa",
  "simi valley": "Ventura",
  "sisquoc": "Santa Barbara",
  "sky valley": "Riverside",
  "sleepy hollow": "Marin",
  "smartsville": "Yuba",
  "smith corner": "Kern",
  "smith river": "Del Norte",
  "snelling": "Merced",
  "soda bay": "Lake",
  "soda springs": "Nevada",
  "solana beach": "San Diego",
  "soledad": "Monterey",
  "solvang": "Santa Barbara",
  "somis": "Ventura",
  "sonoma": "Sonoma",
  "sonoma state university": "Sonoma",
  "sonora": "Tuolumne",
  "soquel": "Santa Cruz",
  "soulsbyville": "Tuolumne",
  "south dos palos": "Merced",
  "south el monte": "Los Angeles",
  "south gate": "Los Angeles",
  "south lake tahoe": "El Dorado",
  "south monrovia island": "Los Angeles",
  "south oroville": "Butte",
  "south pasadena": "Los Angeles",
  "south san francisco": "San Mateo",
  "south san gabriel": "Los Angeles",
  "south san jose hills": "Los Angeles",
  "south taft": "Kern",
  "south whittier": "Los Angeles",
  "spaulding": "Lassen",
  "spreckels": "Monterey",
  "spring garden": "Plumas",
  "spring valley lake": "San Bernardino",
  "springville": "Tulare",
  "squaw valley": "Fresno",
  "squirrel mountain valley": "Kern",
  "st helena": "Napa",
  "stallion springs": "Kern",
  "stanford": "Santa Clara",
  "stanton": "Orange",
  "stebbins": "Kern",
  "stevenson ranch": "Los Angeles",
  "stevinson": "Merced",
  "stinson beach": "Marin",
  "stirling city": "Butte",
  "stockton": "San Joaquin",
  "stones landing": "Lassen",
  "stonyford": "Colusa",
  "stratford": "Kings",
  "strathmore": "Tulare",
  "sugarloaf saw mill": "Tulare",
  "sugarloaf village": "Tulare",
  "suisun city": "Solano",
  "sultana": "Tulare",
  "summerland": "Santa Barbara",
  "sun village": "Los Angeles",
  "sunny slopes": "Mono",
  "sunnyside": "Fresno",
  "sunnyside tahoe city": "Placer",
  "sunnyvale": "Santa Clara",
  "sunol": "Alameda",
  "susanville": "Lassen",
  "sutter": "Sutter",
  "sutter creek": "Amador",
  "swall meadows": "Mono",
  "taft": "Kern",
  "taft heights": "Kern",
  "taft mosswood": "San Joaquin",
  "tahoe vista": "Placer",
  "talmage": "Mendocino",
  "tamalpais homestead valley": "Marin",
  "tancred": "Yolo",
  "tara hills": "Contra Costa",
  "tarina": "Kern",
  "tarpey village": "Fresno",
  "taylorsville": "Plumas",
  "tecopa": "Inyo",
  "tehachapi": "Kern",
  "tehama": "Tehama",
  "temecula": "Riverside",
  "temelec": "Sonoma",
  "temescal valley": "Riverside",
  "temple city": "Los Angeles",
  "templeton": "San Luis Obispo",
  "tennant": "Siskiyou",
  "terminous": "San Joaquin",
  "terra bella": "Tulare",
  "teviston": "Tulare",
  "thermal": "Riverside",
  "thermalito": "Butte",
  "thornton": "San Joaquin",
  "thousand oaks": "Ventura",
  "thousand palms": "Riverside",
  "three rivers": "Tulare",
  "three rocks": "Fresno",
  "tiburon": "Marin",
  "timber cove": "Sonoma",
  "tipton": "Tulare",
  "tobin": "Plumas",
  "tomales": "Marin",
  "tonyville": "Tulare",
  "tooleville": "Tulare",
  "topanga": "Los Angeles",
  "topaz": "Mono",
  "toro canyon": "Santa Barbara",
  "torrance": "Los Angeles",
  "trabuco canyon": "Orange",
  "tracy": "San Joaquin",
  "tranquillity": "Fresno",
  "traver": "Tulare",
  "tres pinos": "San Benito",
  "trinidad": "Humboldt",
  "trinity center": "Trinity",
  "trinity village": "Trinity",
  "trona": "Inyo",
  "trowbridge": "Sutter",
  "truckee": "Nevada",
  "tulare": "Tulare",
  "tulelake": "Siskiyou",
  "tuolumne city": "Tuolumne",
  "tupman": "Kern",
  "turlock": "Stanislaus",
  "tustin": "Orange",
  "tuttle": "Merced",
  "tuttletown": "Tuolumne",
  "twain": "Plumas",
  "twain harte": "Tuolumne",
  "twentynine palms": "San Bernardino",
  "ukiah": "Mendocino",
  "union city": "Alameda",
  "university of california davis": "Yolo",
  "university of california merced": "Merced",
  "university of california santa barbara": "Santa Barbara",
  "upland": "San Bernardino",
  "upper lake": "Lake",
  "vacaville": "Solano",
  "val verde": "Los Angeles",
  "valinda": "Los Angeles",
  "valle vista": "Riverside",
  "vallecito": "Calaveras",
  "vallejo": "Solano",
  "valley acres": "Kern",
  "valley center": "San Diego",
  "valley ford": "Sonoma",
  "valley home": "Stanislaus",
  "valley ranch": "Plumas",
  "valley springs": "Calaveras",
  "valley wells": "Inyo",
  "vandenberg afb": "Santa Barbara",
  "vandenberg village": "Santa Barbara",
  "verdi": "Sierra",
  "vernon": "Los Angeles",
  "victor": "San Joaquin",
  "victorville": "San Bernardino",
  "view park windsor hills": "Los Angeles",
  "villa park": "Orange",
  "vina": "Tehama",
  "vincent": "Los Angeles",
  "vine hill": "Contra Costa",
  "vineyard": "Sacramento",
  "virginia lakes": "Mono",
  "visalia": "Tulare",
  "vista": "San Diego",
  "vista santa rosa": "Riverside",
  "volcano": "Amador",
  "volta": "Merced",
  "walker": "Mono",
  "wallace": "Calaveras",
  "walnut": "Los Angeles",
  "walnut creek": "Contra Costa",
  "walnut grove": "Sacramento",
  "walnut park": "Los Angeles",
  "warm springs": "Riverside",
  "warner valley": "Plumas",
  "wasco": "Kern",
  "washington": "Nevada",
  "waterford": "Stanislaus",
  "waterloo": "San Joaquin",
  "watsonville": "Santa Cruz",
  "waukena": "Tulare",
  "wautec": "Humboldt",
  "wawona": "Mariposa",
  "weaverville": "Trinity",
  "weed": "Siskiyou",
  "weedpatch": "Kern",
  "weitchpec": "Humboldt",
  "weldon": "Kern",
  "weott": "Humboldt",
  "west athens": "Los Angeles",
  "west bishop": "Inyo",
  "west carson": "Los Angeles",
  "west covina": "Los Angeles",
  "west goshen": "Tulare",
  "west hollywood": "Los Angeles",
  "west menlo park": "San Mateo",
  "west modesto": "Stanislaus",
  "west park": "Fresno",
  "west point": "Calaveras",
  "west puente valley": "Los Angeles",
  "west rancho dominguez": "Los Angeles",
  "west sacramento": "Yolo",
  "west whittier los nietos": "Los Angeles",
  "westhaven moonstone": "Humboldt",
  "westlake village": "Los Angeles",
  "westley": "Stanislaus",
  "westminster": "Orange",
  "westmont": "Los Angeles",
  "westmorland": "Imperial",
  "westside": "Fresno",
  "westwood": "Lassen",
  "wheatland": "Yuba",
  "whitehawk": "Plumas",
  "whitewater": "Riverside",
  "whitley gardens": "San Luis Obispo",
  "whitmore": "Shasta",
  "whittier": "Los Angeles",
  "wildomar": "Riverside",
  "wilkerson": "Inyo",
  "williams": "Colusa",
  "williams canyon": "Orange",
  "willits": "Mendocino",
  "willow creek": "Humboldt",
  "willowbrook": "Los Angeles",
  "willows": "Glenn",
  "wilsonia": "Tulare",
  "wilton": "Sacramento",
  "winchester": "Riverside",
  "windsor": "Sonoma",
  "winter gardens": "San Diego",
  "winterhaven": "Imperial",
  "winters": "Yolo",
  "winton": "Merced",
  "wofford heights": "Kern",
  "woodacre": "Marin",
  "woodbridge": "San Joaquin",
  "woodcrest": "Riverside",
  "woodlake": "Tulare",
  "woodland": "Yolo",
  "woodlands": "San Luis Obispo",
  "woodside": "San Mateo",
  "woodville": "Tulare",
  "woodville farm labor camp": "Tulare",
  "woody": "Kern",
  "wrightwood": "San Bernardino",
  "yankee hill": "Butte",
  "yermo": "San Bernardino",
  "yettem": "Tulare",
  "yolo": "Yolo",
  "yorba linda": "Orange",
  "yosemite lakes": "Madera",
  "yosemite valley": "Mariposa",
  "yosemite west": "Mariposa",
  "yountville": "Napa",
  "yreka": "Siskiyou",
  "yuba city": "Sutter",
  "yucaipa": "San Bernardino",
  "yucca valley": "San Bernardino",
  "zayante": "Santa Cruz",
}

/**
 * Place names that occur in more than one county — generally two unrelated
 * communities sharing a name. Callers must treat these as unresolved rather
 * than picking one, since a wrong county routes cases from the wrong region.
 */
export const CENSUS_AMBIGUOUS_PLACES: Record<string, string[]> = {
  "alta sierra": ["Kern","Nevada"],
  "aromas": ["Monterey","San Benito"],
  "bayview": ["Contra Costa","Humboldt"],
  "bear valley": ["Alpine","Mariposa"],
  "centerville": ["Fresno","Shasta"],
  "cold springs": ["El Dorado","Tuolumne"],
  "cottonwood": ["Kern","Shasta"],
  "el sobrante": ["Contra Costa","Riverside"],
  "franklin": ["Merced","Sacramento"],
  "green valley": ["Los Angeles","Solano"],
  "kingvale": ["Nevada","Placer"],
  "kirkwood": ["Alpine","Amador"],
  "lakeside": ["Kern","San Diego"],
  "las flores": ["Orange","Tehama"],
  "lockwood": ["Amador","Monterey"],
  "san miguel": ["Contra Costa","San Luis Obispo"],
  "spring valley": ["Lake","San Diego"],
  "strawberry": ["Marin","Tuolumne"],
  "tahoma": ["El Dorado","Placer"],
  "twin lakes": ["Mono","Santa Cruz"],
}
