import { describe, it, expect } from 'vitest'
import { allLandingPages, type LandingPage } from './seoLandingPages'
import { topicContentBySlug } from './seoLandingPageTopicContent'
import nextConfig from '../../next.config.mjs'

/**
 * Guards the injury-value consolidation.
 *
 * Two families — eight `/how-much-is-a-*-case-worth` and six
 * `/average-*-settlement-california` — were each generated by mapping a row
 * array over one template, so every page shared its body with its siblings.
 * They measured 0.811 and 0.773 median pairwise similarity at around 520 words
 * apiece, while carrying more Search Console demand than anything else on the
 * site and converting none of it. These tests exist so that pattern cannot
 * return quietly, and so the retired URLs keep redirecting.
 */

const GUIDES = [
  '/how-much-is-my-case-worth',
  '/how-much-is-a-car-accident-case-worth',
  '/how-much-is-a-whiplash-case-worth',
  '/how-much-is-a-herniated-disc-case-worth',
  '/how-much-is-a-tbi-case-worth',
  '/how-much-is-a-back-surgery-case-worth',
  '/how-much-is-a-motorcycle-accident-case-worth',
  '/how-much-is-a-pedestrian-accident-case-worth',
]

/**
 * Retired URL -> the guide that absorbed it.
 *
 * The `/average-*` half went first. The `/settlements/*` half followed: those
 * pages were 400-470 words on the same injury as a guide fifteen hundred words
 * longer, so they could only take traffic from it.
 */
const RETIRED: Record<string, string> = {
  '/average-car-accident-settlement-california': '/how-much-is-a-car-accident-case-worth',
  '/average-whiplash-settlement-california': '/how-much-is-a-whiplash-case-worth',
  '/average-herniated-disc-settlement-california': '/how-much-is-a-herniated-disc-case-worth',
  '/average-tbi-settlement-california': '/how-much-is-a-tbi-case-worth',
  '/average-back-surgery-settlement-california': '/how-much-is-a-back-surgery-case-worth',
  '/average-motorcycle-settlement-california': '/how-much-is-a-motorcycle-accident-case-worth',
  '/settlements/whiplash': '/how-much-is-a-whiplash-case-worth',
  '/settlements/whiplash-california': '/how-much-is-a-whiplash-case-worth',
  '/settlements/herniated-disc': '/how-much-is-a-herniated-disc-case-worth',
  '/settlements/herniated-disc-california': '/how-much-is-a-herniated-disc-case-worth',
  '/settlements/tbi-settlement': '/how-much-is-a-tbi-case-worth',
  '/settlements/tbi-california': '/how-much-is-a-tbi-case-worth',
  '/settlements/back-surgery-california': '/how-much-is-a-back-surgery-case-worth',
  '/settlements/motorcycle-accident-settlement': '/how-much-is-a-motorcycle-accident-case-worth',
  '/settlements/pedestrian-accident-settlement': '/how-much-is-a-pedestrian-accident-case-worth',
}

const bySlug = new Map(allLandingPages.map((page) => [page.slug, page]))

function prose(slug: string): string {
  const page = bySlug.get(slug)
  if (!page) throw new Error(`no page at ${slug}`)
  return JSON.stringify({ page, topic: topicContentBySlug[slug] })
}

function words(slug: string): number {
  return prose(slug)
    .replace(/[^a-zA-Z ]+/g, ' ')
    .split(/\s+/)
    .filter(Boolean).length
}

function shingles(value: string, size = 5): Set<string> {
  const parts = value
    .replace(/[^a-zA-Z ]+/g, ' ')
    .toLowerCase()
    .split(/\s+/)
    .filter(Boolean)
  const set = new Set<string>()
  for (let i = 0; i + size <= parts.length; i += 1) set.add(parts.slice(i, i + size).join(' '))
  return set
}

function similarity(a: string, b: string): number {
  const left = shingles(prose(a))
  const right = shingles(prose(b))
  let shared = 0
  for (const gram of left) if (right.has(gram)) shared += 1
  return shared / (left.size + right.size - shared)
}

describe('the injury-value guides', () => {
  it('publishes all eight with topic content', () => {
    for (const slug of GUIDES) {
      expect(bySlug.has(slug), `${slug} is missing`).toBe(true)
      expect(topicContentBySlug[slug], `${slug} has no topic content`).toBeDefined()
    }
  })

  it('gives each one enough substance to answer the question', () => {
    // The generated versions averaged roughly 520 words. Anything near that is
    // the template coming back.
    for (const slug of GUIDES) {
      expect(words(slug), `${slug} is thin`).toBeGreaterThan(1000)
    }
  })

  it('keeps them distinct from one another', () => {
    // The families scored 0.811 and 0.773 against their own siblings. These
    // pages share a subject area, so some overlap is expected and fine; what is
    // not fine is one document published eight times.
    for (let i = 0; i < GUIDES.length; i += 1) {
      for (let j = i + 1; j < GUIDES.length; j += 1) {
        const score = similarity(GUIDES[i], GUIDES[j])
        expect(score, `${GUIDES[i]} vs ${GUIDES[j]}`).toBeLessThan(0.2)
      }
    }
  })

  it('says it is not legal advice on every guide', () => {
    for (const slug of GUIDES) {
      expect(prose(slug).toLowerCase(), `${slug} omits the disclaimer`).toMatch(
        /not a law firm|not legal advice/,
      )
    }
  })

  it('quotes no average or typical settlement figure', () => {
    // The point of retiring the average pages was that the number cannot be
    // produced honestly. Reintroducing one here would undo that, and this
    // codebase has removed fabricated values before.
    for (const slug of GUIDES) {
      const text = prose(slug).toLowerCase()
      expect(text, `${slug} states an average payout`).not.toMatch(
        /average (settlement|payout|recovery|award) (is|of|runs|ranges) /,
      )
      expect(text, `${slug} states a typical payout`).not.toMatch(
        /typical (settlement|payout|recovery) (is|of) \$/,
      )
    }
  })

  it('does not swap the California per-person and per-accident limits', () => {
    // Since January 1, 2025 the minimums are $30,000 per person and $60,000 per
    // accident. Naming only the per-person figure is correct for a single
    // claimant; attaching it to the wrong denominator is not, and the Spanish
    // edition of this content carried exactly that error until it was found.
    for (const slug of GUIDES) {
      const text = prose(slug)
      // Reaching "per accident" from $30,000 without passing "per person" on
      // the way means the figure has been attached to the wrong denominator.
      expect(text, `${slug} calls $30,000 a per-accident limit`).not.toMatch(
        /\$30,000(?:(?!per person)[^.]){0,40}per accident/,
      )
      expect(text, `${slug} calls $60,000 a per-person limit`).not.toMatch(
        /\$60,000(?:(?!per accident)[^.]){0,40}per person/,
      )
    }
  })
})

describe('the retired average-settlement URLs', () => {
  it('publishes none of them as pages', () => {
    for (const slug of Object.keys(RETIRED)) {
      expect(bySlug.has(slug), `${slug} is still published`).toBe(false)
      expect(topicContentBySlug[slug], `${slug} still has topic content`).toBeUndefined()
    }
  })

  it('redirects each to the guide that absorbed it', async () => {
    const redirects = await nextConfig.redirects!()
    const bySource = new Map(redirects.map((rule) => [rule.source, rule]))

    for (const [retired, survivor] of Object.entries(RETIRED)) {
      const rule = bySource.get(retired)
      expect(rule, `${retired} has no redirect`).toBeDefined()
      expect(rule!.destination, retired).toBe(survivor)
      expect(rule!.statusCode, retired).toBe(301)
    }
  })

  it('never redirects to a URL that is not itself published', async () => {
    const redirects = await nextConfig.redirects!()
    const published = new Set(allLandingPages.map((page) => page.slug))
    for (const rule of redirects) {
      if (!rule.destination.startsWith('/how-much-is-')) continue
      expect(published.has(rule.destination), rule.destination).toBe(true)
    }
  })

  it('leaves each injury with exactly one page about what it is worth', () => {
    // The point of the consolidation. Two pages on the value of a whiplash
    // claim compete with each other however differently they are written.
    //
    // Scoped to value intent. `/injuries/whiplash-after-rear-end` describes the
    // injury and `/tools/whiplash-settlement-calculator` computes a range; both
    // answer a different question from "what is it worth" and are meant to
    // coexist with the guide.
    const valueIntent = (slug: string) =>
      slug.startsWith('/settlements/') || slug.startsWith('/how-much-is') || slug.startsWith('/average-')

    for (const subject of ['whiplash', 'herniated-disc', 'tbi', 'back-surgery']) {
      const pages = allLandingPages
        .filter((page: LandingPage) => !page.locale || page.locale === 'en')
        .map((page: LandingPage) => page.slug)
        .filter((slug: string) => slug.includes(subject) && valueIntent(slug))
      expect(pages, `more than one value page covers ${subject}`).toHaveLength(1)
    }
  })

  it('leaves no page still generated from the old row template', () => {
    // The template gave every sibling the same `psychology` and `cta`. If a page
    // reappears carrying those, the seed file came back.
    const templated = allLandingPages.filter(
      (page: LandingPage) =>
        page.psychology === 'I need a realistic estimate before I decide what to do.' ||
        page.psychology === 'I want a benchmark, but I need something specific.',
    )
    expect(templated.map((page) => page.slug)).toEqual([])
  })
})
