import { describe, it, expect } from 'vitest'
import { allLandingPages } from './seoLandingPages'
import { topicContentBySlug } from './seoLandingPageTopicContent'
import nextConfig from '../../next.config.mjs'

/**
 * Guards the insurance consolidation.
 *
 * Fifteen per-carrier URLs were generated by mapping a carrier array over a
 * single template literal. Measured on five-word shingle overlap with the
 * carrier name masked, each family scored 1.000 — one document per family,
 * published five times. These tests exist so that pattern cannot return
 * quietly, and so the URLs it left behind keep redirecting.
 */

const RETIRED_DENIAL_CARRIERS = [
  'state-farm', 'geico', 'progressive', 'allstate', 'farmers',
  'usaa', 'liberty-mutual', 'mercury', 'travelers', 'nationwide',
]
const RETIRED_PROCESS_CARRIERS = ['state-farm', 'geico', 'progressive', 'allstate', 'usaa']

const GUIDES = ['/insurance/claim-denial', '/insurance/settlement-process']

function wordsOf(slug: string): number {
  const page = allLandingPages.find((p) => p.slug === slug)!
  const topic = topicContentBySlug[slug]!
  return [
    page.description,
    page.sections.whyItMatters,
    ...page.sections.whatToTrack,
    page.sections.howClearCaseHelps,
    ...page.faqs.flatMap((f) => [f.q, f.a]),
    topic.scenario,
    ...topic.timeline.flat(),
    ...topic.severityLadder.flat(),
    ...topic.treatmentProgression.flatMap((s) => [s.label, s.copy]),
    ...topic.settlementDrivers,
    ...topic.settlementValueDetails.flatMap((d) => [d.label, d.copy]),
    ...topic.insuranceProblems,
    ...topic.intakeSteps.flatMap((s) => [s.label, s.question]),
  ]
    .join(' ')
    .split(/\s+/)
    .filter(Boolean).length
}

describe('insurance guide consolidation', () => {
  it('publishes both guides with their topic content', () => {
    for (const slug of GUIDES) {
      expect(allLandingPages.find((p) => p.slug === slug), slug).toBeDefined()
      expect(topicContentBySlug[slug], slug).toBeDefined()
    }
  })

  it('no longer publishes a page per carrier', () => {
    const perCarrier = allLandingPages.filter((p) =>
      /^\/insurance\/.+-(denied-claim|settlement-process)$/.test(p.slug),
    )
    expect(perCarrier.map((p) => p.slug)).toEqual([])
  })

  it('keeps every landing page slug unique', () => {
    const slugs = allLandingPages.map((p) => p.slug)
    expect(slugs.length - new Set(slugs).size).toBe(0)
  })

  // The whole point of the merge is that one substantial page replaces five
  // interchangeable ones. A guide that drifts back toward the ~480-word median
  // of the corpus has lost the reason it exists.
  it('gives each guide more depth than the page it replaced', () => {
    for (const slug of GUIDES) {
      expect(wordsOf(slug), slug).toBeGreaterThan(1000)
    }
  })

  it('keeps the two guides covering different ground', () => {
    const [denial, process] = GUIDES.map((slug) => allLandingPages.find((p) => p.slug === slug)!)
    expect(denial.sections.whyItMatters).not.toEqual(process.sections.whyItMatters)
    expect(denial.cluster).not.toEqual(process.cluster)
    const sharedFaqs = denial.faqs.filter((f) => process.faqs.some((g) => g.q === f.q))
    expect(sharedFaqs).toEqual([])
  })
})

describe('retired carrier URLs', () => {
  it('301s every retired URL to the guide that replaced it', async () => {
    const redirects = await nextConfig.redirects!()
    const bySource = new Map(redirects.map((r) => [r.source, r]))

    for (const carrier of RETIRED_DENIAL_CARRIERS) {
      const rule = bySource.get(`/insurance/${carrier}-denied-claim`)
      expect(rule, carrier).toBeDefined()
      expect(rule!.destination).toBe('/insurance/claim-denial')
      expect(rule!.statusCode).toBe(301)
    }

    for (const carrier of RETIRED_PROCESS_CARRIERS) {
      const rule = bySource.get(`/insurance/${carrier}-settlement-process`)
      expect(rule, carrier).toBeDefined()
      expect(rule!.destination).toBe('/insurance/settlement-process')
      expect(rule!.statusCode).toBe(301)
    }
  })

  it('never redirects to a URL that is not itself published', async () => {
    const redirects = await nextConfig.redirects!()
    const published = new Set(allLandingPages.map((p) => p.slug))
    const insuranceTargets = redirects
      .filter((r) => r.destination.startsWith('/insurance/'))
      .map((r) => r.destination)
    for (const target of new Set(insuranceTargets)) {
      expect(published.has(target), target).toBe(true)
    }
  })
})
